apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: demo-aks-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1 
    name: demo-aks-deployment
    kind: Deployment
  minReplicas: 2
  maxReplicas: 64
  metrics:
  - type: Pods
    pods:
      metric:
        name: route_request
      target:
        type: AverageValue
        averageValue: 1
